name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      
      - name: Generate Deployment Package
        run: |
          zip -r deploy.zip . -x '*.git*' -x '*/node_modules/*' -x '*/dist/*'
          
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: auramatch-v2
          environment_name: Auramatch-v2-env
          version_label: deploy-${{ github.sha }}-${{ github.run_number }}
          region: ap-southeast-1
          deployment_package: deploy.zip
          use_existing_version_if_available: true
